// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-2PInc9oTi7K-z-YegiYo8-atD8X_SdU',
    appId: '1:793993504641:web:2826282fe88e8645f06a80',
    messagingSenderId: '793993504641',
    projectId: 'caresync-46175',
    authDomain: 'caresync-46175.firebaseapp.com',
    storageBucket: 'caresync-46175.firebasestorage.app',
    measurementId: 'G-5V00Y6TKH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArBrUI7lquPsgd9TxwvpH07qxj7Mb2SHU',
    appId: '1:793993504641:android:1be988aa85604be3f06a80',
    messagingSenderId: '793993504641',
    projectId: 'caresync-46175',
    storageBucket: 'caresync-46175.firebasestorage.app',
  );
}
